#!/bin/bash
#SBATCH --job-name="saxpy GPU"
#SBATCH --output=saxpy_gpu.out
#SBATCH --partition=gpu
#SBATCH --ntasks=1
#SBATCH --mem=4G
#SBATCH --gpus=1
#SBATCH --time=10:00
#SBATCH --account=ulghpsc

module load EasyBuild/2023a
module load Clang/18.1.8-GCCcore-12.3.0-CUDA-12.2.0

export OMP_TARGET_OFFLOAD=MANDATORY

clang -lm -O3 -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda -o shallow_gpu shallow_gpu.c

./shallow_gpu param_simple.txt