#!/bin/bash -l
#
#SBATCH --exclusive
#SBATCH --job-name="Scalasca profile"
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=4
#SBATCH --time=01:30:00
#SBATCH --mem-per-cpu=2000
#SBATCH --output=scalasca_profile_%j.out

# Loading Scalasca will also load OpenMPI
module load Scalasca

export OMP_PROC_BIND=true
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}

export SRUN_CPUS_PER_TASK=${SLURM_CPUS_PER_TASK}

scalasca -analyze srun ./shallow_combin param_simple.txt